name: publish-latest

on:
  workflow_dispatch:

  workflow_call:

jobs:
  publish:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: release-s3

      - name: Install s3cmd
        run: |
          sudo apt-get update
          sudo apt-get install s3cmd

      - name: Publish to S3
        working-directory: ./scripts
        run: ./publish_to_s3.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
